# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-26 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('mail', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=16)),
                ('text', models.CharField(max_length=200)),
            ],
        ),
    ]
